backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: templateKey
        label: Template key
        widget: hidden
        default: blog-post
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publish date
        widget: datetime
      - name: description
        label: Description
        widget: text
      - name: banner
        label: Banner
        widget: image
      - name: body
        label: Body
        widget: markdown
  - name: listing
    label: Listing
    folder: src/pages/aanbod
    create: true
    slug: "{{slug}}"
    fields:
      - name: templateKey
        label: Template key
        widget: hidden
        default: product-page
      - name: title
        label: Title
        widget: string
      - name: type
        label: Producttype
        widget: select
        options:
          - iMac
          - iPad
          - Macbook
          - Macbook Air
          - Macbook Pro
          - Mac Pro
      - name: size
        label: Formaat (inch)
        widget: number
      - name: release
        label: Release
        widget: object
        fields:
          - name: prefix
            label: Moment
            widget: select
            options:
              - Begin
              - Medio
              - Eind
          - name: year
            label: Jaar
            widget: number
      - name: price
        label: Prijs
        widget: object
        fields:
          - name: old
            label: Originele prijs
            widget: number
          - name: new
            label: Mac Select prijs
            widget: number
      - name: cpu
        label: Processor
        widget: object
        required: false
        fields:
          - name: name
            label: Naam
            widget: string
          - name: speed
            label: Snelheid (GHz)
            widget: number
      - name: ram
        label: Werkgeheugen (GB)
        widget: number
        required: false
      - name: gpu
        label: Grafische kaart
        widget: object
        required: false
        fields:
          - name: name
            label: Naam
            widget: string
          - name: memory
            label: Geheugen (MB)
            widget: number
      - name: storage
        label: Opslag
        widget: object
        required: false
        fields:
          - name: amount
            label: Hoeveelheid (GB)
            widget: number
          - name: type
            label: Type
            widget: select
            options:
              - Harddisk
              - Fusion Drive
              - SSD
      - name: state
        label: Staat
        widget: select
        options:
          - Nieuwstaat
          - Gebruikt
          - Beschadigd
      - name: description
        label: Beschrijving
        widget: text
        required: false
      - name: images
        label: Afbeeldingen
        widget: list
        fields:
          - name: image
            label: Afbeelding
            widget: image
