backend:
  name: git-gateway
  branch: master

display_url: https://mac-select.netlify.com
media_folder: static/assets/images
public_folder: /assets/images

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: src/pages/blog
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: templateKey
        label: Template key
        widget: hidden
        default: blog-post
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publish date
        widget: datetime
      - name: description
        label: Description
        widget: text
      - name: banner
        label: Banner
        widget: image
      - name: body
        label: Body
        widget: markdown
  - name: products
    label: Products
    label_singular: Product
    folder: src/pages/aanbod
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - name: templateKey
        label: Template key
        widget: hidden
        default: product-page
      - name: date
        label: Publish date
        widget: datetime
      - name: spotlight
        label: Is spotlight
        widget: boolean
      - name: title
        label: Title
        widget: string
      - name: type
        label: Producttype
        widget: select
        options:
          - iMac
          - iPad
          - Macbook
          - Macbook Air
          - Macbook Pro
          - Mac Pro
      - name: size
        label: Formaat (inch)
        widget: number
      - name: release
        label: Release
        widget: object
        fields:
          - name: prefix
            label: Moment
            widget: select
            options:
              - Begin
              - Medio
              - Eind
          - name: year
            label: Jaar
            widget: number
      - name: price
        label: Prijs
        widget: object
        fields:
          - name: old
            label: Originele prijs
            widget: number
          - name: new
            label: Mac Select prijs
            widget: number
      - name: cpu
        label: Processor
        widget: object
        required: false
        fields:
          - name: name
            label: Naam
            widget: string
          - name: speed
            label: Snelheid (GHz)
            widget: number
      - name: ram
        label: Werkgeheugen (GB)
        widget: number
        required: false
      - name: gpu
        label: Grafische kaart
        widget: object
        required: false
        fields:
          - name: name
            label: Naam
            widget: string
          - name: memory
            label: Geheugen (MB)
            widget: number
      - name: storage
        label: Opslag
        widget: object
        required: false
        fields:
          - name: amount
            label: Hoeveelheid (GB)
            widget: number
          - name: type
            label: Type
            widget: select
            options:
              - Harddisk
              - Fusion Drive
              - SSD
      - name: accessories
        label: Accessoires
        widget: object
        fields:
          - name: mm
            label: Magic Mouse
            widget: boolean
            required: false
          - name: mt
            label: Magic Trackpad
            widget: boolean
            required: false
          - name: wk
            label: Draadloos toetsenbord
            widget: boolean
            required: false
          - name: nk
            label: Numeriek toetsenbord
            widget: boolean
            required: false
      - name: other
        label: Overig
        widget: object
        fields:
          - name: box
            label: Originele doos aanwezig
            widget: boolean
            required: false
          - name: receipt
            label: Originele bon aanwezig
            widget: boolean
            required: false
          - name: vat
            label: Product is een BTW product
            widget: boolean
            required: false
      - name: state
        label: Staat
        widget: select
        options:
          - Nieuwstaat
          - Gebruikt
          - Beschadigd
      - name: description
        label: Beschrijving
        widget: text
        required: false
      - name: images
        label: Afbeeldingen
        widget: list
        fields:
          - name: image
            label: Afbeelding
            widget: image
